import { LegalPage } from "../components/LegalPage";
import { siteConfig } from "../site-config";
export default function Page(){const mailto=`mailto:${siteConfig.contactEmail}?subject=Solicitud%20sobre%20mis%20datos%20personales`;return <LegalPage title="Política de tratamiento de datos personales" updated={siteConfig.privacyPolicyVersion}>
<p>Esta política explica cómo recopilamos, utilizamos, almacenamos y protegemos los datos de quienes postulan al programa de usuarios fundadores.</p>
<h2>1. Responsable</h2><p><strong>{siteConfig.dataController}</strong>, persona natural establecida en Chile. Canal de consultas y derechos: <a href={mailto}>{siteConfig.contactEmail}</a>.</p>
<h2>2. Personas y datos</h2><p>Tratamos datos de postulantes: nombre, correo, teléfono, región, cantidad de vehículos, tipo de usuario, problema que desean resolver, fecha, autorización y versión del aviso aceptado.</p><p>No solicitamos datos sensibles. No incluyas datos de salud, biométricos, financieros, contraseñas, números de documentos ni datos de terceros en el texto libre.</p>
<h2>3. Finalidades y licitud</h2><p>Con tu consentimiento previo, libre, informado, específico e inequívoco usamos los datos para evaluar y organizar postulaciones, contactarte sobre el programa y mejorar la propuesta mediante información agregada. No vendemos bases ni adoptamos decisiones automatizadas con efectos jurídicos.</p><p>Puedes revocar gratuitamente el consentimiento en cualquier momento, sin efecto retroactivo.</p>
<h2>4. Destinatarios y proveedores</h2><p>Solo acceden el responsable y proveedores necesarios que actúan por cuenta del proyecto. Usamos Google Sheets y Apps Script para recibir y almacenar postulaciones, y OpenAI Sites para publicar el sitio. No cedemos ni vendemos la información a otros responsables.</p>
<h2>5. Tratamiento internacional</h2><p>Google y OpenAI pueden procesar información mediante infraestructura fuera de Chile y aplican condiciones contractuales y medidas de seguridad. Revisaremos las garantías de todo proveedor conforme a los artículos 27 y 28 vigentes desde el 1 de diciembre de 2026.</p>
<h2>6. Conservación</h2><p>Conservaremos cada postulación como máximo doce meses. La eliminaremos antes si deja de ser necesaria, revocas tu consentimiento o procede la supresión, salvo obligación legal o necesidad de antecedentes para reclamaciones.</p>
<h2>7. Derechos</h2><p>Puedes solicitar gratuitamente acceso, rectificación, supresión, oposición, bloqueo temporal y, cuando corresponda, portabilidad, además de retirar tu consentimiento.</p><p>Escribe a <a href={mailto}>{siteConfig.contactEmail}</a> indicando nombre, correo usado, derecho y descripción. Podremos verificar razonablemente tu identidad.</p><p>Acusaremos recibo y responderemos dentro de treinta días corridos, prorrogables una vez. Desde la vigencia de la Ley 21.719 podrás reclamar ante la Agencia si rechazamos o no respondemos oportunamente.</p>
<h2>8. Seguridad</h2><p>Aplicamos acceso restringido, minimización, validación de entradas, protección contra fórmulas maliciosas y revisión de conservación. Los incidentes relevantes serán evaluados, registrados y notificados cuando corresponda.</p>
<h2>9. Cambios</h2><p>La versión y fecha aparecen al comienzo. Los cambios sustanciales no se aplicarán retroactivamente; pediremos nuevo consentimiento cuando corresponda.</p>
</LegalPage>}
